project:
  output-dir: docs
  type: website

website:
  # # not sure what that is...
  # reader-mode: true
  title: "Joffrey Joumaa | portfolio"
  navbar:
    # nav bar always visible when scrolling
    pinned: true
    left:
      - text: "Home"
        href: index.html
      - text: "Notebooks"
        menu:
          - text: "Dataiku Interview"
            href: dataiku_jjoumaa.qmd
          - text: "Saegus Interview"
            href: saegus_jjoumaa.html
          - text: "Booking Interview"
            href: booking_jjoumaa.qmd
      - text: "Webapps"
        menu:
          - text: "DiveMap (Python)"
            href: https://nestrack.duckdns.org/
          - text: "CropRisk (Python)"
            href: https://dashrisk.pythonanywhere.com/
          - text: "CropRisk (R)"
            href: https://joffreyjoumaa.shinyapps.io/shiny_risk/
      - text: "Packages"
        menu:
          - text: "ontodive"
            href: https://sesjo.github.io/ontodive/
      - text: "Resume"
        href: resume_jjoumaa.qmd
    right: 
      - icon: fingerprint
        href: https://orcid.org/0000-0002-2862-0899
      - icon: linkedin
        href: https://www.linkedin.com/in/joffreyjoumaa/
      - icon: github
        href: https://github.com/SESjo
      - text: "About me"
        href: about.qmd

theme:
  light: [cosmo, theme-light.scss]
  dark: [cosmo, theme-dark.scss]
